### ISSUE TITLE
Pretrained weights link is dead

### ISSUE THREAD

**Issue by neuencer** [yijingru/ANCIS-Pytorch#6]
Hi yijingru,

I tried to download your pretrained weights from https://drive.google.com/drive/folders/1sE04a62AHNBjq5f0Z-aaGz9RJ3Nv4nmV?usp=sharing. Unfortunately, the link seems to be dead. Could you provide a new link to the pretrained weights?

Best regards,
Jan

**Comment by yijingru** [comment]
Sorry for my late reply, it should work now.
